USE JPULLEN;

DROP TABLE IF EXISTS Loans;
DROP TABLE IF EXISTS Location;
DROP TABLE IF EXISTS CopiesOfBook;
DROP TABLE IF EXISTS MasterBooks;
DROP TABLE IF EXISTS MasterAuthor;
DROP TABLE IF EXISTS Publisher;
DROP TABLE IF EXISTS Genre;
DROP TABLE IF EXISTS Shifts;
DROP TABLE IF EXISTS Staff;
DROP TABLE IF EXISTS PayRoll;
DROP TABLE IF EXISTS Role;
DROP TABLE IF EXISTS Members;

