INSERT INTO Genre VALUES(0,'Action & Adventure')
INSERT INTO Genre VALUES(1,'Anthology')
INSERT INTO Genre VALUES(2,'Autobiography')
INSERT INTO Genre VALUES(3,'Biography')
INSERT INTO Genre VALUES(4,'Children’s Fiction')
INSERT INTO Genre VALUES(5,'Comic Book or Graphic Novel')
INSERT INTO Genre VALUES(6,'Contemporary Fiction')
INSERT INTO Genre VALUES(7,'Crime')
INSERT INTO Genre VALUES(8,'Detective Story')
INSERT INTO Genre VALUES(9,'Dystopian')
INSERT INTO Genre VALUES(10,'Fable')
INSERT INTO Genre VALUES(11,'Fairy Tale')
INSERT INTO Genre VALUES(12,'Fantasy')
INSERT INTO Genre VALUES(13,'Historical Fiction')
INSERT INTO Genre VALUES(14,'History')
INSERT INTO Genre VALUES(15,'Horror')
INSERT INTO Genre VALUES(16,'Memoir')
INSERT INTO Genre VALUES(17,'Mystery')
INSERT INTO Genre VALUES(18,'Mythology')
INSERT INTO Genre VALUES(19,'Narrative Non-Fiction')
INSERT INTO Genre VALUES(20,'Poetry')
INSERT INTO Genre VALUES(21,'Romance')
INSERT INTO Genre VALUES(22,'Satire')
INSERT INTO Genre VALUES(23,'Science Fiction')
INSERT INTO Genre VALUES(24,'Science Fantasy')
INSERT INTO Genre VALUES(25,'Self-Help')
INSERT INTO Genre VALUES(26,'Short Story')
INSERT INTO Genre VALUES(27,'Thriller')
INSERT INTO Genre VALUES(28,'Western')
INSERT INTO Genre VALUES(29,'Young Adult')

SELECT * FROM Genre;