

INSERT INTO Publisher VALUES(0,'Penguin Random House')
INSERT INTO Publisher VALUES(1,'HarperCollins')
INSERT INTO Publisher VALUES(2,'Simon & Schuster')
INSERT INTO Publisher VALUES(3,'Hachette Book Group')
INSERT INTO Publisher VALUES(4,'Macmillan Publishers')
INSERT INTO Publisher VALUES(5,'Scholastic Corporation')
INSERT INTO Publisher VALUES(6,'Bloomsbury Publishing')
INSERT INTO Publisher VALUES(7,'Oxford University Press')
INSERT INTO Publisher VALUES(8,'Cambridge University Press')
INSERT INTO Publisher VALUES(9,'Houghton Mifflin Harcourt')
INSERT INTO Publisher VALUES(10,'Wiley')
INSERT INTO Publisher VALUES(11,'Pearson Education')
INSERT INTO Publisher VALUES(12,'Springer Nature')
INSERT INTO Publisher VALUES(13,'Elsevier')
INSERT INTO Publisher VALUES(14,'Taylor & Francis')
INSERT INTO Publisher VALUES(15,'SAGE Publications')
INSERT INTO Publisher VALUES(16,'MIT Press')
INSERT INTO Publisher VALUES(17,'University of Chicago Press')
INSERT INTO Publisher VALUES(18,'Yale University Press')
INSERT INTO Publisher VALUES(19,'Harvard University Press')
INSERT INTO Publisher VALUES(20,'Knopf Doubleday Publishing Group')
INSERT INTO Publisher VALUES(21,'Crown Publishing Group')
INSERT INTO Publisher VALUES(22,'Ballantine Books')
INSERT INTO Publisher VALUES(23,'Bantam Books')
INSERT INTO Publisher VALUES(24,'Anchor Books')
INSERT INTO Publisher VALUES(25,'Vintage Books')
INSERT INTO Publisher VALUES(26,'Pantheon Books')
INSERT INTO Publisher VALUES(27,'Random House')
INSERT INTO Publisher VALUES(28,'Doubleday')
INSERT INTO Publisher VALUES(29,'Delacorte Press')
INSERT INTO Publisher VALUES(30,'William Morrow')
INSERT INTO Publisher VALUES(31,'Avon Books')
INSERT INTO Publisher VALUES(32,'Harper Perennial')
INSERT INTO Publisher VALUES(33,'Harper Voyager')
INSERT INTO Publisher VALUES(34,'Ecco')
INSERT INTO Publisher VALUES(35,'Amistad Press')
INSERT INTO Publisher VALUES(36,'Gallery Books')
INSERT INTO Publisher VALUES(37,'Atria Books')
INSERT INTO Publisher VALUES(38,'Scribner')
INSERT INTO Publisher VALUES(39,'Touchstone')
INSERT INTO Publisher VALUES(40,'Little, Brown and Company')
INSERT INTO Publisher VALUES(41,'Little, Brown Books for Young Readers')
INSERT INTO Publisher VALUES(42,'Grand Central Publishing')
INSERT INTO Publisher VALUES(43,'Orbit Books')
INSERT INTO Publisher VALUES(44,'Mulholland Books')
INSERT INTO Publisher VALUES(45,'Back Bay Books')
INSERT INTO Publisher VALUES(46,'Flatiron Books')
INSERT INTO Publisher VALUES(47,'Farrar, Straus and Giroux')
INSERT INTO Publisher VALUES(48,'Picador')
INSERT INTO Publisher VALUES(49,'Henry Holt and Company')
INSERT INTO Publisher VALUES(50,'Metropolitan Books')
INSERT INTO Publisher VALUES(51,'St. Martins Press')
INSERT INTO Publisher VALUES(52,'Minotaur Books')
INSERT INTO Publisher VALUES(53,'Tor Books')
INSERT INTO Publisher VALUES(54,'Forge Books')
INSERT INTO Publisher VALUES(55,'Dutton')
INSERT INTO Publisher VALUES(56,'Putnam')
INSERT INTO Publisher VALUES(57,'Riverhead Books')
INSERT INTO Publisher VALUES(58,'Viking Press')
INSERT INTO Publisher VALUES(59,'Penguin Books')
INSERT INTO Publisher VALUES(60,'Puffin Books')
INSERT INTO Publisher VALUES(61,'Ladybird Books')
INSERT INTO Publisher VALUES(62,'Hodder & Stoughton')
INSERT INTO Publisher VALUES(63,'Transworld Publishers')
INSERT INTO Publisher VALUES(64,'Corgi Books')
INSERT INTO Publisher VALUES(65,'Black Swan')
INSERT INTO Publisher VALUES(66,'Doubleday UK')
INSERT INTO Publisher VALUES(67,'Headline Publishing Group')
INSERT INTO Publisher VALUES(68,'Orion Publishing Group')
INSERT INTO Publisher VALUES(69,'Weidenfeld & Nicolson')
INSERT INTO Publisher VALUES(70,'Victor Gollancz')
INSERT INTO Publisher VALUES(71,'Faber & Faber')
INSERT INTO Publisher VALUES(72,'John Murray Press')
INSERT INTO Publisher VALUES(73,'Profile Books')
INSERT INTO Publisher VALUES(74,'Canongate Books')
INSERT INTO Publisher VALUES(75,'Sceptre')
INSERT INTO Publisher VALUES(76,'Pan Macmillan')
INSERT INTO Publisher VALUES(77,'Picador UK')
INSERT INTO Publisher VALUES(78,'Mantle')
INSERT INTO Publisher VALUES(79,'Two Roads')
INSERT INTO Publisher VALUES(80,'Quercus')
INSERT INTO Publisher VALUES(81,'Constable & Robinson')
INSERT INTO Publisher VALUES(82,'Little, Brown UK')
INSERT INTO Publisher VALUES(83,'Virago Press')
INSERT INTO Publisher VALUES(84,'Serpents Tail')
INSERT INTO Publisher VALUES(85,'Atlantic Books')
INSERT INTO Publisher VALUES(86,'Granta Books')
INSERT INTO Publisher VALUES(87,'Walker Books')
INSERT INTO Publisher VALUES(88,'Usborne Publishing')
INSERT INTO Publisher VALUES(89,'Chicken House')
INSERT INTO Publisher VALUES(90,'Egmont Books')
INSERT INTO Publisher VALUES(91,'Pushkin Press')
INSERT INTO Publisher VALUES(92,'Oneworld Publications')
INSERT INTO Publisher VALUES(93,'Bitter Lemon Press')
INSERT INTO Publisher VALUES(94,'Polygon')
INSERT INTO Publisher VALUES(95,'Birlinn')
INSERT INTO Publisher VALUES(96,'Saraband')
INSERT INTO Publisher VALUES(97,'Harlequin Enterprises')
INSERT INTO Publisher VALUES(98,'McClelland & Stewart')
INSERT INTO Publisher VALUES(99,'House of Anansi Press')
INSERT INTO Publisher VALUES(100,'Annick Press')
INSERT INTO Publisher VALUES(101,'Groundwood Books')
INSERT INTO Publisher VALUES(102,'Dundurn Press')
INSERT INTO Publisher VALUES(103,'Tundra Books')
INSERT INTO Publisher VALUES(104,'Arsenal Pulp Press')
INSERT INTO Publisher VALUES(105,'Anvil Press')
INSERT INTO Publisher VALUES(106,'Fitzhenry & Whiteside')
INSERT INTO Publisher VALUES(107,'Allen & Unwin')
INSERT INTO Publisher VALUES(108,'Text Publishing')
INSERT INTO Publisher VALUES(109,'Scribe Publications')
INSERT INTO Publisher VALUES(110,'Hardie Grant Books')
INSERT INTO Publisher VALUES(111,'Black Inc.')
INSERT INTO Publisher VALUES(112,'University of Queensland Press')
INSERT INTO Publisher VALUES(113,'Fremantle Press')
INSERT INTO Publisher VALUES(114,'Wakefield Press')
INSERT INTO Publisher VALUES(115,'S. Fischer Verlag')
INSERT INTO Publisher VALUES(116,'Rowohlt Verlag')
INSERT INTO Publisher VALUES(117,'Suhrkamp Verlag')
INSERT INTO Publisher VALUES(118,'Hanser Verlag')
INSERT INTO Publisher VALUES(119,'dtv Verlagsgesellschaft')
INSERT INTO Publisher VALUES(120,'Kiepenheuer & Witsch')
INSERT INTO Publisher VALUES(121,'Aufbau Verlag')
INSERT INTO Publisher VALUES(122,'Piper Verlag')
INSERT INTO Publisher VALUES(123,'Luchterhand Literaturverlag')
INSERT INTO Publisher VALUES(124,'Droemer Knaur')
INSERT INTO Publisher VALUES(125,'Gallimard')
INSERT INTO Publisher VALUES(126,'Hachette Livre')
INSERT INTO Publisher VALUES(127,'Flammarion')
INSERT INTO Publisher VALUES(128,'Éditions du Seuil')
INSERT INTO Publisher VALUES(129,'Albin Michel')
INSERT INTO Publisher VALUES(130,'Robert Laffont')
INSERT INTO Publisher VALUES(131,'Grasset & Fasquelle')
INSERT INTO Publisher VALUES(132,'Calmann-Lévy')
INSERT INTO Publisher VALUES(133,'Fayard')
INSERT INTO Publisher VALUES(134,'Stock')
INSERT INTO Publisher VALUES(135,'Mondadori')
INSERT INTO Publisher VALUES(136,'Einaudi')
INSERT INTO Publisher VALUES(137,'Feltrinelli')
INSERT INTO Publisher VALUES(138,'Rizzoli')
INSERT INTO Publisher VALUES(139,'Adelphi Edizioni')
INSERT INTO Publisher VALUES(140,'Planeta')
INSERT INTO Publisher VALUES(141,'Santillana')
INSERT INTO Publisher VALUES(142,'Anagrama')
INSERT INTO Publisher VALUES(143,'Alfaguara')
INSERT INTO Publisher VALUES(144,'Tusquets Editores')
INSERT INTO Publisher VALUES(145,'AST Publishing House')
INSERT INTO Publisher VALUES(146,'Eksmo')
INSERT INTO Publisher VALUES(147,'Corpus Publishers')
INSERT INTO Publisher VALUES(148,'Azbooka-Atticus')
INSERT INTO Publisher VALUES(149,'Mann, Ivanov and Ferber')
INSERT INTO Publisher VALUES(150,'Shinchosha')
INSERT INTO Publisher VALUES(151,'Kodansha')
INSERT INTO Publisher VALUES(152,'Shogakukan')
INSERT INTO Publisher VALUES(153,'Hakusensha')
INSERT INTO Publisher VALUES(154,'Kadokawa Corporation')
INSERT INTO Publisher VALUES(155,'Bungeishunju')
INSERT INTO Publisher VALUES(156,'Iwanami Shoten')
INSERT INTO Publisher VALUES(157,'Chikumashobo')
INSERT INTO Publisher VALUES(158,'Hayakawa Publishing')
INSERT INTO Publisher VALUES(159,'East Press')
INSERT INTO Publisher VALUES(160,'Renmin Literature Publishing House')
INSERT INTO Publisher VALUES(161,'CITIC Press Group')
INSERT INTO Publisher VALUES(162,'SDX Joint Publishing Company')
INSERT INTO Publisher VALUES(163,'Shanghai Translation Publishing House')
INSERT INTO Publisher VALUES(164,'Guangxi Normal University Press')
INSERT INTO Publisher VALUES(165,'Penguin India')
INSERT INTO Publisher VALUES(166,'HarperCollins India')
INSERT INTO Publisher VALUES(167,'Rupa Publications')
INSERT INTO Publisher VALUES(168,'Westland Books')
INSERT INTO Publisher VALUES(169,'Juggernaut Books')
INSERT INTO Publisher VALUES(170,'Aleph Book Company')
INSERT INTO Publisher VALUES(171,'Speaking Tiger Books')
INSERT INTO Publisher VALUES(172,'Tulika Publishers')
INSERT INTO Publisher VALUES(173,'Pratham Books')
INSERT INTO Publisher VALUES(174,'Scholastic India')
INSERT INTO Publisher VALUES(175,'Restless Books')
INSERT INTO Publisher VALUES(176,'Archipelago Books')
INSERT INTO Publisher VALUES(177,'Europa Editions')
INSERT INTO Publisher VALUES(178,'Open Letter Books')
INSERT INTO Publisher VALUES(179,'Deep Vellum Publishing')
INSERT INTO Publisher VALUES(180,'Soho Press')
INSERT INTO Publisher VALUES(181,'Akashic Books')
INSERT INTO Publisher VALUES(182,'Melville House')
INSERT INTO Publisher VALUES(183,'Coffee House Press')
INSERT INTO Publisher VALUES(184,'Graywolf Press')
INSERT INTO Publisher VALUES(185,'Tin House Books')
INSERT INTO Publisher VALUES(186,'Algonquin Books')
INSERT INTO Publisher VALUES(187,'Sourcebooks')
INSERT INTO Publisher VALUES(188,'Quirk Books')
INSERT INTO Publisher VALUES(189,'Chronicle Books')
INSERT INTO Publisher VALUES(190,'Abrams Books')
INSERT INTO Publisher VALUES(191,'Workman Publishing')
INSERT INTO Publisher VALUES(192,'Rodale Books')
INSERT INTO Publisher VALUES(193,'Thomas Nelson')
INSERT INTO Publisher VALUES(194,'Zondervan')
INSERT INTO Publisher VALUES(195,'Tyndale House Publishers')
INSERT INTO Publisher VALUES(196,'Baker Publishing Group')
INSERT INTO Publisher VALUES(197,'InterVarsity Press')
INSERT INTO Publisher VALUES(198,'Kensington Publishing')
INSERT INTO Publisher VALUES(199,'Entangled Publishing')

SELECT * FROM Publisher;